#Program to demonstate multi variate linear regression

#sales prediction using advertisement through TV, Radio and Newspaper

In [109]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [110]:
# Read the given CSV file, and view some sample records
advertising = pd.read_csv("Z:/Machine_learning Dr. Vimina/Machine Learning 2026/BCA H 2026/ML Lab Programs/linearregression code/Company_data.csv")
advertising

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [111]:
# Shape of our dataset
advertising.shape

(200, 4)

In [112]:
# Info our dataset
advertising.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [113]:
# Describe our dataset
advertising.describe()

               TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

Multiple Linear Regression

In [114]:
# Creating X and y
X = advertising[['TV', 'Radio','Newspaper']]
y = advertising['Sales']

In [115]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7,test_size=0.3,random_state=100)

In [116]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [117]:
mlr = LinearRegression()
mlr.fit(X_train_scaled, y_train)

LinearRegression()

In [118]:
# Display the y intercept and the feature coefficients
print("Intercept: ", mlr.intercept_)
print("Coefficients:")
list(zip(X, mlr.coef_))

Intercept:  15.005714285714287
Coefficients:

[('TV', np.float64(4.981018752198338)),
 ('Radio', np.float64(1.6593977110638853)),
 ('Newspaper', np.float64(0.14181393313850643))]

In [119]:
#Prediction of test set
y_pred_mlr= mlr.predict(X_test)
#Predicted values
print("Prediction for test set: {}".format(y_pred_mlr))

Prediction for test set: [ 125.58401653 1259.15333639  764.14559367 1163.33034202 1285.26514296
 1056.46045064  735.72334855 1005.89961391 1167.71088857 1171.59547826
  623.94005363 1222.27065782  308.60940893  986.80156002  472.60442334
  493.49742239  820.5896636   880.7102585   891.51753914  611.7102694
 1124.82324118  673.44688388 1074.95200635  957.55811619  973.96334003
 1194.08843782 1171.81926772  428.37115269 1009.08472477  687.34277626
  434.5991711   374.25603944  638.55426262  987.09518246  285.91504171
  664.52506654  505.90425156  867.40621425 1130.28399952 1017.1886305
 1135.24742204  916.06578724  875.78669161 1116.20476105  647.89340506
  483.29389111  184.37877679 1302.50039687  399.00201004  213.37743443
 1065.14790085  939.47870095  454.63273674  743.1379174  1114.77746743
  308.27118719  111.96408773  208.55517465 1039.93274424  508.27688631]

c:\Users\viminaer\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

In [121]:
#Actual value and the predicted value
mlr_diff = pd.DataFrame({'Actual value': y_test, 'Predicted value': y_pred_mlr})
mlr_diff.head()

     Actual value  Predicted value
126           6.6       125.584017
104          20.7      1259.153336
99           17.2       764.145594
92           19.4      1163.330342
111          21.8      1285.265143

In [125]:
#Model Evaluation
print("MAE :", round(mean_absolute_error(y_test, y_pred_mlr), 2))
print("MSE :", round(mean_squared_error(y_test, y_pred_mlr), 2))
print("RMSE:", round(np.sqrt(mean_squared_error(y_test, y_pred_mlr)), 2))
print("R2 Score:", round(r2_score(y_test, y_pred_mlr), 2))

MAE : 768.18
MSE : 700685.45
RMSE: 837.07
R2 Score: -35723.9